{ config, pkgs, lib, ... }:

let
  customPapirusIcons = pkgs.papirus-icon-theme.override {
    color = "Brown"; 
  };
in
{
  # ── GTK Theme Base ───────────────────────────────────────────────────────────
  gtk = {
    enable = true;

    theme = {
      name    = "adw-gtk3-dark";
      package = pkgs.adw-gtk3;
    };

    iconTheme = {
      name    = "Papirus-Dark";
    };

    # ── GTK3 Named Color Overrides ─────────────────────────────────────────────
    gtk3.extraCss = ''
      /* 1. Pull in the raw color variables generated by Caelestia */
      @import url("file:///home/jivan/.config/caelestia/colors.css");

      /* 2. Map those variables to the exact token names adw-gtk3 expects */
      /* Note: Replace var(--your-variable) with the exact names found inside your colors.css */

      /* Core Window */
      @define-color window_bg_color        var(--background, var(--md-sys-color-background));
      @define-color window_fg_color        var(--on-background, var(--md-sys-color-on-background));
      @define-color view_bg_color          var(--surface, var(--md-sys-color-surface));
      @define-color view_fg_color          var(--on-surface, var(--md-sys-color-on-surface));

      /* Accents */
      @define-color accent_bg_color        var(--primary, var(--md-sys-color-primary));
      @define-color accent_fg_color        var(--on-primary, var(--md-sys-color-on-primary));
      @define-color accent_color           var(--primary, var(--md-sys-color-primary));

      /* Headerbars & Sidebars */
      @define-color headerbar_bg_color     var(--surface-container, var(--md-sys-color-surface-container));
      @define-color headerbar_fg_color     var(--on-surface, var(--md-sys-color-on-surface));
      @define-color headerbar_backdrop_color var(--surface-container, var(--md-sys-color-surface-container));
      @define-color headerbar_border_color var(--outline-variant, var(--md-sys-color-outline-variant));

      /* Cards & Lists */
      @define-color card_bg_color          var(--surface-container-low, var(--md-sys-color-surface-container-low));
      @define-color card_fg_color          var(--on-surface, var(--md-sys-color-on-surface));

      /* Popovers & Dialogs */
      @define-color popover_bg_color       var(--surface-container-high, var(--md-sys-color-surface-container-high));
      @define-color popover_fg_color       var(--on-surface, var(--md-sys-color-on-surface));
      @define-color dialog_bg_color        var(--surface-container-high, var(--md-sys-color-surface-container-high));
      @define-color dialog_fg_color        var(--on-surface, var(--md-sys-color-on-surface));

      /* Semantic Feedback states */
      @define-color error_bg_color         var(--error-container, var(--md-sys-color-error-container));
      @define-color error_fg_color         var(--error, var(--md-sys-color-error));
      @define-color error_color            var(--error, var(--md-sys-color-error));
    '';

    # ── GTK4 (libadwaita apps) ─────────────────────────────────────────────────
    gtk4.extraCss = ''
      /* Mirror the structural mapping perfectly for libadwaita applications */
      @import url("file:///home/jivan/.local/state/caelestia/scheme.json");

      /* Core Window */
      @define-color window_bg_color        var(--background, var(--md-sys-color-background));
      @define-color window_fg_color        var(--on-background, var(--md-sys-color-on-background));
      @define-color view_bg_color          var(--surface, var(--md-sys-color-surface));
      @define-color view_fg_color          var(--on-surface, var(--md-sys-color-on-surface));

      /* Accents */
      @define-color accent_bg_color        var(--primary, var(--md-sys-color-primary));
      @define-color accent_fg_color        var(--on-primary, var(--md-sys-color-on-primary));
      @define-color accent_color           var(--primary, var(--md-sys-color-primary));

      /* Headerbars & Sidebars */
      @define-color headerbar_bg_color     var(--surface-container, var(--md-sys-color-surface-container));
      @define-color headerbar_fg_color     var(--on-surface, var(--md-sys-color-on-surface));
      @define-color headerbar_backdrop_color var(--surface-container, var(--md-sys-color-surface-container));
      @define-color headerbar_border_color var(--outline-variant, var(--md-sys-color-outline-variant));

      /* Cards & Lists */
      @define-color card_bg_color          var(--surface-container-low, var(--md-sys-color-surface-container-low));
      @define-color card_fg_color          var(--on-surface, var(--md-sys-color-on-surface));

      /* Popovers & Dialogs */
      @define-color popover_bg_color       var(--surface-container-high, var(--md-sys-color-surface-container-high));
      @define-color popover_fg_color       var(--on-surface, var(--md-sys-color-on-surface));
      @define-color dialog_bg_color        var(--surface-container-high, var(--md-sys-color-surface-container-high));
      @define-color dialog_fg_color        var(--on-surface, var(--md-sys-color-on-surface));
    '';
  };

  # ── Required packages ────────────────────────────────────────────────────────
  home.packages = with pkgs; [
    adw-gtk3
    papirus-icon-theme
    gsettings-desktop-schemas   
  ];

  # ── Apply theme via gsettings at session start ────────────────────────────────
  wayland.windowManager.hyprland.settings.exec-once = [
    "gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'"
    "gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'"
    "gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'"
    "papirus-folders -c teal" 
  ];
}