return {
  primary = "{{ colors.primary.hex_stripped }}",
  secondary = "{{ colors.secondary.hex_stripped }}",
  tertiary = "{{ colors.tertiary.hex_stripped }}",
  neutral = "{{ colors.surface.hex_stripped }}",
  neutralVariant = "{{ colors.surface_variant.hex_stripped }}",
  
  background = "{{ colors.background.hex_stripped }}",
  onBackground = "{{ colors.on_background.hex_stripped }}",
  surface = "{{ colors.surface.hex_stripped }}",
  surfaceDim = "{{ colors.surface_dim.hex_stripped }}",
  surfaceBright = "{{ colors.surface_bright.hex_stripped }}",
  surfaceContainerLowest = "{{ colors.surface_container_lowest.hex_stripped }}",
  surfaceContainerLow = "{{ colors.surface_container_low.hex_stripped }}",
  surfaceContainer = "{{ colors.surface_container.hex_stripped }}",
  surfaceContainerHigh = "{{ colors.surface_container_high.hex_stripped }}",
  surfaceContainerHighest = "{{ colors.surface_container_highest.hex_stripped }}",
  onSurface = "{{ colors.on_surface.hex_stripped }}",
  surfaceVariant = "{{ colors.surface_variant.hex_stripped }}",
  onSurfaceVariant = "{{ colors.on_surface_variant.hex_stripped }}",
  inverseSurface = "{{ colors.inverse_surface.hex_stripped }}",
  inverseOnSurface = "{{ colors.inverse_on_surface.hex_stripped }}",
  outline = "{{ colors.outline.hex_stripped }}",
  outlineVariant = "{{ colors.outline_variant.hex_stripped }}",
  shadow = "{{ colors.shadow.hex_stripped }}",
  scrim = "{{ colors.scrim.hex_stripped }}",
  surfaceTint = "{{ colors.surface_tint.hex_stripped }}",
  
  onPrimary = "{{ colors.on_primary.hex_stripped }}",
  primaryContainer = "{{ colors.primary_container.hex_stripped }}",
  onPrimaryContainer = "{{ colors.on_primary_container.hex_stripped }}",
  inversePrimary = "{{ colors.inverse_primary.hex_stripped }}",
  
  onSecondary = "{{ colors.on_secondary.hex_stripped }}",
  secondaryContainer = "{{ colors.secondary_container.hex_stripped }}",
  onSecondaryContainer = "{{ colors.on_secondary_container.hex_stripped }}",
  
  onTertiary = "{{ colors.on_tertiary.hex_stripped }}",
  tertiaryContainer = "{{ colors.tertiary_container.hex_stripped }}",
  onTertiaryContainer = "{{ colors.on_tertiary_container.hex_stripped }}",
  
  error = "{{ colors.error.hex_stripped }}",
  onError = "{{ colors.on_error.hex_stripped }}",
  errorContainer = "{{ colors.error_container.hex_stripped }}",
  onErrorContainer = "{{ colors.on_error_container.hex_stripped }}",
  
  primaryFixed = "{{ colors.primary_fixed.hex_stripped }}",
  primaryFixedDim = "{{ colors.primary_fixed_dim.hex_stripped }}",
  onPrimaryFixed = "{{ colors.on_primary_fixed.hex_stripped }}",
  onPrimaryFixedVariant = "{{ colors.on_primary_fixed_variant.hex_stripped }}",
  
  secondaryFixed = "{{ colors.secondary_fixed.hex_stripped }}",
  secondaryFixedDim = "{{ colors.secondary_fixed_dim.hex_stripped }}",
  onSecondaryFixed = "{{ colors.on_secondary_fixed.hex_stripped }}",
  onSecondaryFixedVariant = "{{ colors.on_secondary_fixed_variant.hex_stripped }}",
  
  tertiaryFixed = "{{ colors.tertiary_fixed.hex_stripped }}",
  tertiaryFixedDim = "{{ colors.tertiary_fixed_dim.hex_stripped }}",
  onTertiaryFixed = "{{ colors.on_tertiary_fixed.hex_stripped }}",
  onTertiaryFixedVariant = "{{ colors.on_tertiary_fixed_variant.hex_stripped }}",

  -- ANSI Terminal Color Maps
  term0 = "{{ colors.surface_container_highest.hex_stripped }}",
  term1 = "{{ colors.error.hex_stripped }}",
  term2 = "{{ colors.primary.hex_stripped }}",
  term3 = "{{ colors.tertiary.hex_stripped }}",
  term4 = "{{ colors.secondary.hex_stripped }}",
  term5 = "{{ colors.inverse_primary.hex_stripped }}",
  term6 = "{{ colors.primary_fixed_dim.hex_stripped }}",
  term7 = "{{ colors.on_surface.hex_stripped }}",
  term8 = "{{ colors.outline.hex_stripped }}",
  term9 = "{{ colors.error.hex_stripped }}",
  term10 = "{{ colors.primary.hex_stripped }}",
  term11 = "{{ colors.tertiary_fixed.hex_stripped }}",
  term12 = "{{ colors.secondary_fixed.hex_stripped }}",
  term13 = "{{ colors.tertiary_fixed_dim.hex_stripped }}",
  term14 = "{{ colors.primary_fixed.hex_stripped }}",
  term15 = "{{ colors.on_surface_variant.hex_stripped }}",

  -- Catppuccin Designator Tokens
  rosewater = "{{ colors.primary_fixed.hex_stripped }}",
  flamingo = "{{ colors.primary_fixed_dim.hex_stripped }}",
  pink = "{{ colors.tertiary_fixed.hex_stripped }}",
  mauve = "{{ colors.primary.hex_stripped }}",
  red = "{{ colors.error.hex_stripped }}",
  maroon = "{{ colors.error_container.hex_stripped }}",
  peach = "{{ colors.tertiary.hex_stripped }}",
  yellow = "{{ colors.tertiary_container.hex_stripped }}",
  green = "{{ colors.secondary.hex_stripped }}",
  teal = "{{ colors.secondary_container.hex_stripped }}",
  sky = "{{ colors.inverse_primary.hex_stripped }}",
  sapphire = "{{ colors.primary_container.hex_stripped }}",
  blue = "{{ colors.secondary.hex_stripped }}",
  lavender = "{{ colors.primary_fixed.hex_stripped }}",

  -- UI/State Elements
  klink = "{{ colors.primary.hex_stripped }}",
  klinkSelection = "{{ colors.primary.hex_stripped }}",
  kvisited = "{{ colors.inverse_primary.hex_stripped }}",
  kvisitedSelection = "{{ colors.inverse_primary.hex_stripped }}",
  knegative = "{{ colors.error.hex_stripped }}",
  knegativeSelection = "{{ colors.error.hex_stripped }}",
  kneutral = "{{ colors.secondary.hex_stripped }}",
  kneutralSelection = "{{ colors.secondary.hex_stripped }}",
  kpositive = "{{ colors.primary.hex_stripped }}",
  kpositiveSelection = "{{ colors.primary.hex_stripped }}",

  -- Text & Semantic Overlays
  text = "{{ colors.on_surface.hex_stripped }}",
  subtext1 = "{{ colors.on_surface_variant.hex_stripped }}",
  subtext0 = "{{ colors.outline.hex_stripped }}",
  overlay2 = "{{ colors.outline_variant.hex_stripped }}",
  overlay1 = "{{ colors.surface_variant.hex_stripped }}",
  overlay0 = "{{ colors.surface_container_highest.hex_stripped }}",
  surface2 = "{{ colors.surface_container_high.hex_stripped }}",
  surface1 = "{{ colors.surface_container.hex_stripped }}",
  surface0 = "{{ colors.surface_container_low.hex_stripped }}",
  base = "{{ colors.surface.hex_stripped }}",
  mantle = "{{ colors.surface_dim.hex_stripped }}",
  crust = "{{ colors.surface_container_lowest.hex_stripped }}",

  -- Success Blocks
  success = "{{ custom_colors.success.hex_stripped | default(value=colors.primary.hex_stripped) }}",
  onSuccess = "{{ custom_colors.on_success.hex_stripped | default(value=colors.on_primary.hex_stripped) }}",
  successContainer = "{{ custom_colors.success_container.hex_stripped | default(value=colors.primary_container.hex_stripped) }}",
  onSuccessContainer = "{{ custom_colors.on_success_container.hex_stripped | default(value=colors.on_primary_container.hex_stripped) }}",
}